@include('layouts.templateAuditor.head')
@include('layouts.partials.sidebar')
@include('layouts.partials.header')
@yield('content')
@include('layouts.templateAuditor.footer')
@include('layouts.templateAuditor.footer-scripts')